(
 (web-mode . ((web-mode-attr-indent-offset . 2)
              (web-mode-markup-indent-offset . 2)
              (web-mode-code-indent-offset . 2)
              (web-mode-css-indent-offset . 2)
              (web-mode-part-padding . 2)
              (web-mode-style-padding . 0)
              (web-mode-block-padding . 2)
              (web-mode-script-padding . 0))
           )
 )
